# SonarCloud settings

sonar.organization=prabu-12
sonar.projectKey=Prabu-12_sonar-demo
sonar.projectName=SonarQube Demo
sonar.projectVersion=1.0

# Source settings

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/coverage.xml

# Python settings

sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml

# SonarCloud URL

sonar.host.url=https://sonarcloud.io
